### ISSUE TITLE
screen blanking since last flatpak dependincy update 

### ISSUE THREAD

**Issue by pflanzenandi** [Guldoman/mpv_inhibit_gnome#4] opened 2022-10-09 20:05 UTC
The update removed the gnome.SessionManager override entry. But applying the override again, didn't fix the screen go blank.
Besides that, nothing has changes in my setup.

Am using `flatpak override --user --talk-name=org.gnome.SessionManager io.mpv.Mpv`

**Comment by Guldoman** [comment] 2022-10-10 17:30
This should be fixed by #5. Could you confirm?
Also it looks like this plugin will be included in the flatpak release of mpv by default in the near future (flathub/io.mpv.Mpv#94).

**Comment by Guldoman** [comment] 2022-10-10 21:39
Closing for now. Feel free to reopen if the issue is still present.

**Closed as completed by Guldoman** 2022-10-10 21:39 UTC

**Comment by Guldoman** [comment] 2022-10-11 22:28
The plugin has been integrated into the Flatpak release, so you should remove the version you manually installed to avoid problems (`~/.var/app/io.mpv.Mpv/config/mpv/scripts/mpv_inhibit_gnome.so`).

**Comment by pflanzenandi** [comment] 2022-10-12 06:01
I already did. Thanks for your support!
